version: "3.9"

services:
    jasperjakobsnl:
        image: "jasperjakobs-nl:${GITHUB_RUN_ID}"
        container_name: jasperjakobs-nl
        networks:
            - traefik
        labels:
            traefik.enable: "true"
            traefik.http.routers.jasperjakobsnl.entrypoints: "websecure"
            traefik.http.routers.jasperjakobsnl.rule: "Host(`jasperjakobs.nl`)"
            traefik.http.routers.jasperjakobsnl.tls: "true"
            traefik.http.routers.jasperjakobsnl.tls.certresolver: "lets-encrypt"
            traefik.docker.network: "traefik"

networks:
  traefik:
    external: true
