name: Docker Image CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file ./deployment/Dockerfile -t jasperjakobs-nl:$GITHUB_RUN_ID
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy the Docker image
      run: docker compose -f ./deployment/docker-compose.yml up -d
